name: "CI: tests, linter and build"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
      - dependencies
      - 'dependencies-**'
  pull_request:
    branches:
      - main
      - dependencies

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip-CI]')"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20, 22, 24]
    name: "node:${{ matrix.node-version }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run build
        run: npm run build

      - name: Run tests
        run: npm test -- --ci --coverage --runInBand --coverageReporters=text
